# For more info on HTTP files go to https://aka.ms/vs/httpfile
### Create a new task with high priority
POST https://localhost:7266/task
Content-Type: application/json

{
  "Name": "Hight Priority Task",
  "Priority": 1
}

### Get videos
GET https://localhost:7266/video
Content-Type: application/json